Added mappings for some new MITPE topics
mitodl/open-discussions pull request #3179
Opened 2020-10-06 21:42 UTC by rhysyngsun

#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Fixes #3178 

#### What's this PR do?
Maps a couple new topics that showed up

#### How should this be manually tested?
Run `./manage.py backpopulate_mitpe_data` and verify courses that have these topics on https://professional.mit.edu/course-catalog are correctly mapped.

2020-10-07 17:39 UTC, abeglova approved these changes
👍

2020-10-07 18:02 UTC, pdpinch requested changes
Sorry, I refined my thinking a bit since last night.

2020-10-07 18:02 UTC, pdpinch commented on course_catalog/constants.py
> +    "Digital Transformation": ["Business", "Information Technology"],
```suggestion
    "Digital Transformation": ["Information Technology"],
```
"Business" is too broad a match for this. I think just "Information Technology" is OK.

2020-10-07 18:02 UTC, pdpinch commented on course_catalog/constants.py
> +    "Legal Tech": ["Social Science", "Legal Studies"],
```suggestion
    "Legal Tech": ["Information Technology", "Legal Studies"],
```

Based on the courses, I don't think these are a broad match for "Social Science" either. But I do think ""nformation Technology" is a fair match.

2020-10-08 19:35 UTC, pdpinch approved these changes

2020-10-08 19:47 UTC, merged