Upgrade ocw-data-parser to version 0.29.2
mitodl/open-discussions pull request #3448
Opened 2021-07-01 19:37 UTC by annagav

#### What are the relevant tickets?
N/A

#### What's this PR do?
Upgrade ocw-data-parser to version 0.29.2 that includes the conversion of srt files to vtt

#### How should this be manually tested?
nothing should break

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2021-07-06 22:22 UTC, pdpinch commented on requirements.txt
>      #   smart-open
Do we need boto _and_ boto3?

2021-07-06 22:23 UTC, pdpinch commented on requirements.txt
> +    # via -r requirements.in
Why do we have django-hijack in ocw-data-parser?

2021-07-07 15:31 UTC, noisecapella approved these changes

2021-07-07 16:07 UTC, noisecapella requested changes
Actually this needs an additional change. You need to add `create_vtt_files=True` to `OCWParser` in `course_catalog/api` to activate it

2021-07-07 16:59 UTC, annagav commented
@noisecapella I updated the PR. Thank you

2021-07-07 17:23 UTC, noisecapella approved these changes
Thanks, the output JSON looks good now

2021-07-07 17:24 UTC, merged