OCW Next Webhook Updates
mitodl/open-discussions pull request #3510
Opened 2022-02-18 03:06 UTC by abeglova

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots

#### What are the relevant tickets?
https://github.com/mitodl/ocw-studio/issues/1005

#### What's this PR do?
This updates the ocw next webhook to expect data from concourse and not s3.

#### Any background context you want to provide?
This should be tested with
https://github.com/mitodl/ocw-studio/pull/1028

2022-02-18 21:26 UTC, mbertrand requested changes

2022-02-18 21:26 UTC, mbertrand commented on course_catalog/views.py
> +                kwargs={"course_prefixes": [prefix], "force_overwrite": False}
Also, `get_ocw_next_course` is throwing an error:
```
celery_1   | botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

In my testing I was trying course `11-382-water-diplomacy-spring-2021`, which is the value for the `prefix` key sent in the webhook, but in the S3 bucket the full path is actually `courses/11-382-water-diplomacy-spring-2021/data.json` (and `courses` comes from the site's starter config).  Will make a note on that PR.

2022-02-24 14:45 UTC, mbertrand approved these changes
looks good! 👍   Have `OPEN_DISCUSSIONS_WEBHOOK_KEY` and `OCW_NEXT_WEBHOOK_KEY` been added to salt-ops?

2022-02-24 15:31 UTC, abeglova commented
Thanks! I made a salt-ops pr
https://github.com/mitodl/salt-ops/pull/1509

2022-02-24 16:27 UTC, mbertrand requested changes
There's still `OCW_NEXT_WEBHOOK_KEY` in settings.py

2022-02-24 16:59 UTC, mbertrand approved these changes
👍

2022-02-24 18:57 UTC, merged