New API filters for new open
mitodl/open-discussions pull request #3877
Opened 2023-03-14 15:38 UTC by JenniWhitman

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2023-03-16 18:44 UTC, abeglova requested changes
Doesn't look like the filters work when combined with the existing /new and /featured filters. Otherwise, this looks great

2023-03-16 18:44 UTC, abeglova commented on course_catalog/views.py
> +        kwargs = request.body
I don't think this line is needed

2023-03-16 19:11 UTC, abeglova approved these changes
LGTM

2023-03-16 19:23 UTC, abeglova commented
Oh yeah - I should have caught that sorry. I missed that the platform filter was to get micromasters. That information is in the "offered_by" field

2023-03-16 19:35 UTC, abeglova commented
Yeah it's confusing that micromasters is in the PlatformType array in
https://github.com/mitodl/open-discussions/blob/master/course_catalog/constants.py#L28/. I don't think anything actually has micromasters as a platform

2023-03-16 19:38 UTC, JenniWhitman commented
TBH looks like it's just for that mapping?

2023-03-16 19:47 UTC, abeglova commented
Yeah - we probably don't use it much but conceptually platform is useful information about a course - the site on which the course is offered vs the organization at mit that is offering it

2023-03-17 18:43 UTC, JenniWhitman commented
The code is up for re-review and the description has been updated.

2023-03-17 19:22 UTC, merged