Cc/no default en
mitodl/open-discussions pull request #3961
Opened 2023-04-24 15:14 UTC by ChristopherChudzicki

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2023-04-25 20:44 UTC, ChristopherChudzicki commented on frontends/ol-search-ui/src/util.tsx
> +import ISO6391 from "iso-639-1"
We had been using [locale-code](https://www.npmjs.com/package/locale-code) for language names. Swap to [iso-639-1](https://www.npmjs.com/package/iso-639-1?activeTab=readme). These packages are by the same author & `language-code depends` on `iso-639-1`, so we already had it as a dependency. 

The difference is:
- `iso-639-1` expects a language code... 'en', 'fr', etc
- `locale-code` expects a locale-code, `en-US`, `en-GB`, `zh-CN`, etc

**The reason to swap is:**
- we had been appending a country code 'US' to **all** language codes. That was arbitrary and confusing, but was required to `locale-code`.

2023-04-26 13:53 UTC, ChristopherChudzicki commented on frontends/ol-search-ui/src/util.test.ts
> +  })
This whole test suite is new, but these two tests are the changed behavior. Previously they would have returned "en-US".

2023-04-26 19:47 UTC, mbertrand requested changes
Works for  `../infinite/search`, but English is still showing up as the default under `../learn/search` via [frontends/open_discussions/src/components/ExpandedLearningResourceDisplay.js](https://github.com/mitodl/open-discussions/blob/f0d300bd6b480836f291d8ff5f860bfc6faeaec8/frontends/open-discussions/src/components/ExpandedLearningResourceDisplay.js#L331)

2023-04-27 19:45 UTC, ChristopherChudzicki commented
> Works for ../infinite/search, but English is still showing up as the default under ../learn/search via [frontends/open_discussions/src/components/ExpandedLearningResourceDisplay.js](https://github.com/mitodl/open-discussions/blob/f0d300bd6b480836f291d8ff5f860bfc6faeaec8/frontends/open-discussions/src/components/ExpandedLearningResourceDisplay.js#L331)

That was deliberate, though in this case the bug fix is super simple so probably worthfixing both cases.

If a less trivial issue comes up, maybe worth more of a discussion.

2023-04-28 16:43 UTC, mbertrand approved these changes
👍

2023-04-28 18:52 UTC, merged