Cc/pytest
mitodl/open-discussions pull request #4119
Opened 2023-06-26 17:58 UTC by ChristopherChudzicki

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2023-06-26 18:00 UTC, ChristopherChudzicki commented on scripts/test/test_suite.sh
> -docker-compose run watch npm run-script coverage
There is not currently a coverage command.

2023-06-28 16:55 UTC, ChristopherChudzicki commented on scripts/test/python_tests.sh
This is what we use in other non-tox projects, e.g., https://github.com/mitodl/ocw-studio/blob/master/scripts/test/python_tests.sh

_`black` runs separately on CI, so I didn't include it in this._

2023-06-30 14:16 UTC, mbertrand requested changes
Works great, just a couple suggestions, but since tests are passing on CI anyway they probably aren't critical

2023-06-30 14:16 UTC, mbertrand commented on tox.ini
> -    OCW_WEBHOOK_KEY=fake_key
Some of these aren't in the ci.yml file and/or pytest.ini file, might be good to make them all consistent?  For example `OPEN_DISCUSSIONS_NOTIFICATION_EMAIL_BACKEND` (xpro, mitxonline have the equivalent env in both ci.yml and pytest.ini)

2023-06-30 14:31 UTC, ChristopherChudzicki commented on .github/workflows/ci.yml
> -          NODE_ENV: 'production'
- `NODE_ENV` shouldn't affect the python tests at all, so I don't see any point in setting it.
- `DEBUG=false` was previously being set in both `tox.ini` and `ci.yaml`, with same value. Now it's set in `pytest.ini`. I don't think there's any reason to set it in both places.

2023-06-30 18:53 UTC, ChristopherChudzicki commented
@mbertrand I did start a discussion post about the `pytest-dotenv` idea I mentioned in slack: https://github.com/mitodl/hq/discussions/1836

2023-06-30 21:10 UTC, mbertrand approved these changes
👍

2023-07-05 13:04 UTC, merged